DROP TABLE T_DIARY_ENTRY IF EXISTS;

DROP TABLE T_DIARY_USER_ROLE IF EXISTS;

DROP TABLE T_DIARY_USER IF EXISTS;

CREATE TABLE T_DIARY_USER (
  id INTEGER IDENTITY PRIMARY KEY,
  name VARCHAR(255),
  email  VARCHAR(255),
  password_hash  VARCHAR(255)
);


CREATE TABLE T_DIARY_USER_ROLE (
  id INTEGER IDENTITY PRIMARY KEY,
  role VARCHAR(255),
  user_id  INTEGER
);


CREATE TABLE T_DIARY_ENTRY (
  id INTEGER IDENTITY PRIMARY KEY,
  text VARCHAR(1000),
  user_id  INTEGER
);